Update 02-cqt-40-preparing-for-query-tuning.adoc
A semi colon is necessary at the end of the MATCH commands otherwise the following error is returned 'RETURN can only be used at the end of the query (line 1, column 11 (offset: 10)) "MATCH (n) RETURN max(id(n))"'

Invoking the CALL apoc.warmup.run calls gives the error below in the Broswer Sandbox:
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.warmup.run`: Caused by: java.lang.NoSuchMethodError: 'org.neo4j.io.pagecache.tracing.cursor.PageCursorTracer org.neo4j.kernel.api.KernelTransaction.pageCursorTracer()'